import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import AuthProvider from './AuthProvider'
import { ThemeProvider } from '@/components/theme-provider'
import SelectedDaysProvider from '@/contexts/selectedDays-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-background p-4 text-foreground`}>
				<AuthProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<SelectedDaysProvider>{children}</SelectedDaysProvider>
					</ThemeProvider>
				</AuthProvider>
			</body>
		</html>
	)
}
